[package]
name = "restate"
description = "A simple state machine library"
repository = "https://github.com/Neo-Ciber94/restate"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"
keywords = ["state-machine"]
